server:
  port: 8005

spring:
  application:
    name: basketService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


